import type { Metadata } from 'next';
import { LandingPageClient } from '@/components/landing/LandingPageClient';

// OG / Twitter images are auto-generated by Next.js from
// src/app/opengraph-image.tsx + src/app/twitter-image.tsx.
export const metadata: Metadata = {
  title: "Bilim Nuru — O'quv markaz uchun CRM + LMS",
  description:
    "O'quv markazlar uchun to'liq boshqaruv tizimi. O'quvchilar, guruhlar, to'lovlar, dars jadvali va tahlillar bir joyda.",
  openGraph: {
    title: "Bilim Nuru — O'quv markaz uchun CRM + LMS",
    description:
      "O'quv markazlar uchun to'liq boshqaruv tizimi. O'quvchilar, guruhlar, to'lovlar, dars jadvali va tahlillar bir joyda.",
  },
  twitter: {
    card: 'summary_large_image',
    title: "Bilim Nuru — O'quv markaz uchun CRM + LMS",
    description: "O'quv markazlar uchun to'liq boshqaruv tizimi.",
  },
  // Allow indexing for the public landing page
  robots: { index: true, follow: true },
};

export default function LandingPage() {
  return <LandingPageClient />;
}
